### PR TITLE
feat(synced-lyrics): Better-Lyrics Styling for Synced-Lyrics

### PR DESCRIPTION
**Pull request by kimjammer**
This PR reimplements the CSS styles and animations for synced-lyrics so that it is more like the lyrics view for Spotify or the YT music mobile apps.

Yesterday, I found [boidushya/better-lyrics](https://github.com/boidushya/better-lyrics) and while it's great, it's a web browser extension so you can't install it into this app. So, I spent an afternoon porting the CSS over from that into this pr.

This PR is a draft because:
1.  The code style & css variable names need to be updated (if you want) - I left the original css variable names so it would be clear what's from better-lyrics
2. The new CSS overrides the old "Line effect" settings and that code would need to be removed
3. better-lyrics is GPLv3 and idk how the "same license" clause applies + I want to get @boidushya 's blessing for this port
(Assuming boidushya has ping on mention turned on: Would you be okay with this few dozen line CSS port? Would you mind if I eventually (not this pr) ported the romanization and translation features as well?)

What do you think? I'm open for discussion.

https://github.com/user-attachments/assets/d1cb7325-4276-4417-a942-a94ce87cae8e

### CODE REVIEW

**Comment by boidushya** [comment]
Love this! You have my full support for the port. If you want - happy to create a channel for this port in our discord so we can keep things in sync :))

**Comment by Dzheremi2** [comment]
I love the original synced-lyrics line effect. You should probaly make enabling Better-lyrics style optional. Better-lyrics line effect is too big to me.

**Comment by ArjixWasTaken** [comment]
Ideally this should be merged after https://github.com/th-ch/youtube-music/pull/2383

**Comment by ArjixWasTaken** [comment]
@kimjammer no need to "port" romanization or translation features from someone else's code

**Comment by kimjammer** [comment]
> Ideally this should be merged after #2383

I would love for #2383 to be merged as well, but I didn't want to wait that long lol (and I don't want you to feel pressured). I actually did most of the dev for this pr on your branch, so it will still work when your pr gets merged in!

**Comment by kimjammer** [comment]
> @kimjammer no need to "port" romanization or translation features from someone else's code and there is an open discussion for that [here](https://github.com/th-ch/youtube-music/discussions/2382)
> 
> they are on my TODO list for after I am done with my current PR (not saying that you can't do that urself, but it is smth simple enough to not need to be copied over)

I should have clarified: the "port" is referring to the CSS, I don't really care where the romanization or the translations come from. For reference, the better lyrics CSS for the romanization & translation 
image

**Comment by kimjammer** [comment]
Alrighty! PR is ready for review - (none of the repo contributors have even said if they think this pr is a good idea yet lol)

1. Code has been cleaned up ✅ 
2. New styling has been implemented as "Fancy" line effect & old line effects have been reimplemented ✅ 
3. Permission granted from original author ✅ 

I took a random guess at how i18n was supposed to be done, if there's more lmk.

**Comment by Rairof** [comment]
THIS IS EXACTLY WHAT I WAS LOOKING FOR!
can you also make just the 3 lyrics show up and make rest above and below invisible to not make the lyrics page crowded and  look clean?
similar to this-
image

**Comment by ArjixWasTaken** [comment]
I think this will get out of hand if everyone who has an opinion makes a request.
Stuff that is purely about the appearance of smth should fall under community made themes.

https://github.com/th-ch/youtube-music/issues/2540

**Comment by kimjammer** [comment]
Maintainers, lmk if you have opinions or changes to request.
As far as #2540 goes, the CSS animations used here require changes to the text rendering code, which obviously can't be done just in CSS. Maybe think of this PR as being closer to "bringing feature parity (pretty default synced lyrics) from mobile apps" rather than "Adding CSS choices".
PR is ready to be merged on my end.

**Review by JellyBrick — COMMENTED** [review]
I'll merge this PR after #2383 is merged.

**Comment by JellyBrick** [comment]
Thanks for your contribution!

**Review by JellyBrick — APPROVED** [review]

**Pull request merged**
