### PR TITLE
"Start at login" to "Start at PC login"

### PR DESCRIPTION
**Pull request by inson1**
Fixes:  #1426 
I think this could be enough. But if somebody has better idea, please share it.

### CODE REVIEW

**Comment by JellyBrick** [comment]
How about "Auto-launch at startup"?

**Comment by inson1** [comment]
@JellyBrick 
What about "Auto-launch at PC startup"  (I like to be specific, so its clear and there is no phone support anyway)
Should I Change something, because of breaking change? Is there some migration tool?

**Comment by ArjixWasTaken** [comment]
I assume PC Login means that it runs whenever the user logins, not whenever the pc is powered on.
Logging out and logging back in would still count.

It is misleading to say pc startup

**Comment by inson1** [comment]
@ArjixWasTaken @JellyBrick So in that case "Start at PC login"? Or better ideas?

**Comment by inson1** [comment]
@JellyBrick ?

**Comment by JellyBrick** [comment]
> @JellyBrick ?

we're now using Weblate

**Pull request closed without merging**
