### PR TITLE
feat(api-server): remote control api

### PR DESCRIPTION
**Pull request by Su-Yong**
# Summary
- WIP
- Implement API server
- hono.js (zero-deps)
- Validating inputs with ZOD
- JWT for authorization
- Swagger (OpenAPI)

# Notes

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Please add versioning 🙏

**Comment by ArjixWasTaken** [comment]
Huh, I resolved the conflict and Snyk is now mad at me :(

**Comment by iryis** [comment]
What's blocking this from being merged currently? I'd love to adapt my integrations based on this PR

**Comment by ArjixWasTaken** [comment]
I'll give this a thorough look tomorrow.
As for why it is not merged, I think it is still in progress.

**Comment by ArjixWasTaken** [comment]
I squashed the commits and resolved the conflict, you can find it [here](https://github.com/ArjixWasTaken/youtube-music/commit/a6bcf1e4871b00a85c39039705ada4a13fb0563a).

(Note that I won't be opening a PR to merge that branch into this one, it is just for testing)

--

I ran into an issue, I couldn't authenticate using the bearer token given to me by the api.
Steps taken:
1. Send POST to `/auth/{id}` (`id`=`a`) and receive a json response that contains the JWT
2. Attempt to use any of the APIs endpoints other than `/auth/{id}` and provide the JWT in the form `Authorization: Bearer {JWT}`
3. Receive an `Unauthorized` response

PS: I had the auth strategy to none.

**Comment by JellyBrick** [comment]
TODO: processing CORS with `hono/cors`

**Comment by JustMrPhoenix** [comment]
Hey, who is responsible for this PR? I'd love to move this along for all the cool integrations to be possible. If there is still changes needed I'm willing to work on them. Please let me know if I should take over this feature @JellyBrick. Kinda painful to see it stuck in limbo for this long 🫠

**Review by JellyBrick — APPROVED** [review]

**Comment by JellyBrick** [comment]
@JustMrPhoenix merged

**Comment by SurajBhari** [comment]
i am having issue using the api key. 
i am on /swagger page and got a access token. upon adding that token to authorize on top of page I should be able to tryout routes. 

but it keeps on saying unauthorized 

this is the curl request it generates. what is wrong here ? 
```
curl -X 'POST' \
  'http://localhost:26538/api/v1/toggle-play' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer {   "accessToken": "eyJhFaciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjkiLCJpYXQiOjE3MzU5MjkyNzJ9.5kCWqMddF1bBgwi6QzTVkO4hGYumZ1QLoFH9rEqin_Y" }' \
  -d ''
  
  ```

**Comment by Zerwin** [comment]
I had to disable and enable the plugin for it to start working, maybe that'll also fix it for you

**Pull request merged**
