### PR TITLE
Use ; instead of space for play/pause.

### LINKED ISSUE #741: Play/pause dbus control does not work until play button is clicked
**Steps to reproduce**

1. Turn off "Resume last song when app starts" option
2. Turn on "shortcuts" plugin to enable dbus interface
3. Restart application, start any playlist.
4. Verify with dbus that status is "playing":

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.youtube-music \
  /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
  string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' \
  | grep '"Playing"'
   variant       string "Playing"
```

5. use dbus command to stop the playback:

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.youtube-music \
  /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
```

**Expected behaviout:**
Playback stops

**Actual behaviour**
Application is still playing music, but the dbus status is "Paused":

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.youtube-music \
  /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
  string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'
method return time=1654605627.143655 sender=:1.2169 -> destination=:1.2180 serial=15 reply_serial=2
   variant       string "Paused"
```

**Workaround**

If you click on "pause" button with mouse, the issue is fixed and the app works ok until the next restart

### PR DESCRIPTION
**Pull request by lukaszg84**
fix #741

### CODE REVIEW

**Comment by Araxeus** [comment]
FYI this pr can be automatically linked to the issue and close it when its merged

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

(just write `fix #741`)

**Comment by lukaszg84** [comment]
Seems that after your comment it is linked already.

How long does it take between the fix and deb package being released?

**Comment by Araxeus** [comment]
> Seems that after your comment it is linked already.

Nope it's still not linked, you need to edit your original post and then it will link it

> How long does it take between the fix and deb package being released?

Well it requires multiple steps:
1. The PR gets merged (depends on @th-ch)
2. New app version is released (depends on @th-ch)
deb files should be included in the release

if you are talking about arch linux then you need to wait for a 3rd step: the aur maintainer needs to upload the new version

**Review by th-ch — APPROVED** [review]
Looks good, thanks for the fix!

**Pull request merged**
