### PR TITLE
feat: plugin auto-importer with `vite-plugin-resolve`

### PR DESCRIPTION
**Pull request by JellyBrick**
cc @ArjixWasTaken @Su-Yong

### CODE REVIEW

**Review by Su-Yong — APPROVED** [review]

**Comment by ArjixWasTaken** [comment]
Instead of having a named export, how about having a default export?

That way, you don't need to alias the imported constant every time.

**Comment by JellyBrick** [comment]
> Instead of having a named export, how about having a default export?
> 
> That way, you don't need to alias the imported constant every time.

https://basarat.gitbook.io/typescript/main-1/defaultisbad

For the above reasons, I wanted to avoid using the `default export`. What do you think?

**Comment by ArjixWasTaken** [comment]
Hmm, then what about having a different named export for each context?
Just like `feat/codegen`.

**Comment by JellyBrick** [comment]
> Hmm, then what about having a different named export for each context? Just like `feat/codegen`.

Before I do this, I want to rename `front.ts` to `renderer.ts` and `back.ts` to `main.ts`.
(`frontPluginList` -> `rendererPluginList`, `backPluginList` -> `mainPluginList`)

So, is it okay if I merge this pull request before doing a rename task?

**Pull request merged**
