### PR TITLE
Mpris support

### PR DESCRIPTION
**Pull request by itzmanish**
Fixed conflicts with master branch.
Tested and working with playerctl

### CODE REVIEW

**Comment by jrabinow** [comment]
His @itzmanish thank you very much for this new feature.

I'm afraid that this is a rather large PR: would it be possible for us to minimize its size?
 - by using git-rebase instead of git-merge?
 - by using git-cherry-pick instead of git-merge?
 - by allowing `th-ch:mpris` branch to stay back in time and letting @th-ch deal with fast-forwarding?

**Comment by itzmanish** [comment]
Or let me simply create another PR with cherry pick.

**Comment by itzmanish** [comment]
We can close this and new PR is on https://github.com/th-ch/youtube-music/pull/395

**Comment by jrabinow** [comment]
I'll let you close this PR, the only thing I can do here is comment

**Comment by Araxeus** [comment]
> We can close this and new PR is on #395

Yes so close this one 😅

**Comment by itzmanish** [comment]
Let @th-ch do the closing part.

**Comment by th-ch** [comment]
Thanks for the contribution on Mpris, https://github.com/th-ch/youtube-music/pull/395 has been merged, closing this one!

**Pull request closed without merging**
