### PR TITLE
experimental faster adblocker

### PR DESCRIPTION
**Pull request by Araxeus**
This requires user testing.

Anyone that can test and report how it works for them would be greatly appreciated !

Either clone and build this branch, or download from https://github.com/Zo-Bro-23/youtube-music/releases/tag/v1.19.0

### CODE REVIEW

**Comment by Lucasamiel0406** [comment]
Due to the new dependency update messing with the current plugin, tested this variation to report.

Used it for approximately 3 hours straight, during this time I've seen no ads (including at start) nor bad performance, scrolling feels smooth. At least for me, it's a good replacement for the current plugin.

**Comment by Araxeus** [comment]
I think i'll add a menu checkbox to the adblocker plugin called `beta` or `experimental` which enables this functionality

(since i'm still not 100% sure about this and would like more feedback before completely replacing the current one)

**Review by th-ch — COMMENTED** [review]
It seems to work fine, does it also block tracking?

**Comment by th-ch** [comment]
Closing this one, implementation has been done in https://github.com/th-ch/youtube-music/pull/1134 - thanks for the idea!

**Comment by Araxeus** [comment]
Thanks for finishing this up, I haven't had time to code much lately :)

**Pull request closed without merging**
