### PR TITLE
Fix incorrect Google alert caused by changing user agent coresponding to current platform

### PR DESCRIPTION
**Pull request by konhi**
Solves #327

### CODE REVIEW

**Review by Araxeus — CHANGES_REQUESTED** [review]
Could be slightly simplified using [electron-is](https://github.com/delvedor/electron-is) (it is already used throughout this program)
```js
const userAgent = 
	is.darwin() ? userAgents.mac :
	is.windows() ? userAgents.windows :
	userAgents.linux;
```
(also because you are currently trying to change the value of a const after initialization)
but anyway did you check that google OAuth works? there is a comment saying firefox must be forced for it to work

**Comment by konhi** [comment]
> Could be slightly simplified using electron-is (it is already used throughout this program and imported in index.js line 

Thanks! This code looks much prettier! 💕

> (also because you were trying to change the value of a const after initialization)

Is it a bad practice? If so, could you please give some reference? I'm not really a javascript expert! 😅

> but anyways did you check that google OAuth works? there is a comment saying firefox must be forced for it to work

Good question! If you mean logging in, yes, it worked for me and Google didn't even alert me about anything suspicious! Anyway, I think it may be better option to still use Firefox user-agent.

**Comment by Araxeus** [comment]
> Is it a bad practice? If so, could you please give some reference? I'm not really a javascript expert! 😅

Well const = constant which means immutable value, shouldn't be changed after giving it its initial value.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables#constants_in_javascript

If the value is supposed to change later, you would probably use `let` instead of `const`
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables#declaring_a_variable

**Review by th-ch — APPROVED** [review]
Looks good, thanks for the improvement! ✅

**Pull request merged**
