### PR TITLE
refactor: new plugin system

### LINKED ISSUE #1258: QOL: Reimagining the plugin system.
## About

When I started my, now failed, typescript rewrite, I decided to have an entirely new plugin system.

Although I didn't keep my word in migrating to typescript, thankfully @JellyBrick did it, and did a better job on it.
So, with TypeScript aside, I'd like to discuss how plugins are written.

The current way feels too barbaric, it feels, dare I say, dirty.

## Proposal

What I propose is for plugins to be first class citizens of this codebase.
In my, now dead, fork I got inspired by [Vencord](https://github.com/Vendicated/Vencord) and came up with

```typescript
import { definePlugin } from '../utils/Plugin'

export default definePlugin({
  name: 'Disable Autoplay',
  authors: ['th-ch', 'Araxeus', 'ArjixWasTaken'],

  front: {
    events: {
      PlayerApiLoaded({ api }) {
        api.addEventListener('videodatachange', (name) => {
          const video = document.querySelector('video')
          if (!video) return

          if (name === 'dataloaded') {
            api.pauseVideo()

            return (video.ontimeupdate = (e) => e.target!.pause())
          }

          video.ontimeupdate = null
        })
      }
    }
  }
})
```

For comparison here is the current plugin:
```typescript
export default () => {
  const timeUpdateListener = (e: Event) => {
    if (e.target instanceof HTMLVideoElement) {
      e.target.pause();
    }
  };

  document.addEventListener('apiLoaded', (apiEvent) => {
    apiEvent.detail.addEventListener('videodatachange', (name: string) => {
      if (name === 'dataloaded') {
        apiEvent.detail.pauseVideo();
        document.querySelector<HTMLVideoElement>('video')?.addEventListener('timeupdate', timeUpdateListener);
      } else {
        document.querySelector<HTMLVideoElement>('video')?.removeEventListener('timeupdate', timeUpdateListener);
      }
    });
  }, { once: true, passive: true });
};
```

The current plugin system doesn't satisfy many needs, and it makes it hard to keep everything typed (with types).
Having a well-defined structure for plugins, allows us to more efficiently organise the code.

(and it warms my heart)

----

## Implementation

Currently the way I implemented that in my dead fork is uhh...ugly.
The plugin logic and all is nice, but I did some dirty stuff to share the plugin code between the electron contexts.

I have gained a lot of experience making vite/rollup plugins since, so I can redo it in a nice way.

## Considerations

Before I attempt a naive PR for this, I'd like your thoughts, discussing with you first would be more beneficial than having to do many changes down the line.

**So give me your opinions!**

---

@JellyBrick, @th-ch 

Get pinged!

### LINKED ISSUE #1380: Why doesnt the plugins have spaces?
I think it would look better. (I mean in menu)

### LINKED ISSUE #1386: [Bug]: `injectCSS` not working on `dev` environment (`pnpm dev`)
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

18cd4c0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631)

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

_No response_

### Expected Behavior

- `insertCSS` must work normally like when using `pnpm start` (= `electron-vite preview`)

### Actual Behavior

- `insertCSS` doesn't work when using `pnpm dev`

### Additional Information

_No response_

### LINKED ISSUE #1436: Plugin in-app-menu: Why does have options if there is only one option? and not just on vs off with Check mark?

### PR DESCRIPTION
**Pull request by Su-Yong**
# Explain
This PR is based on the below 3 sentence

1. All plugin's codes must exist `plugins/*` folder (ex: not in `src/index.ts`)
2. All plugins are strongly typed
3. All plugins have 4 types of sub plugin (main, renderer, preload, menu)

The first idiom leads 2 sub idioms
1. The plugin can be injected with some context (can handle external code)
2. Plugin config is defined in `plugin/*` folder

Thus, We designed a new plugin structure.

# Plugin Structure
```
[plugin-folder]
  └ index.ts
```
- `index.ts`: it must be export `createPlugin` as default (required)

> [!WARNING]
> **IF YOU NEED MORE INFORMATION OF THIS PLUGIN SYSTEM, READ `/src/utils/*`**

# Example
- index.ts
```ts
import style from './style.css?inline'; // import style as inline

export default createPlugin({
  name: 'Plugin Label',
  description: 'Awesome Plugin description',
  restartNeeded: true, // if value is true, ytmusic show restart dialog
  config: {
    enabled: false,
  }, // your custom config
  stylesheets: [style], // your custom style,
  menu: async ({ getConfig, setConfig }) => {
    // All *Config methods are wrapped Promise<T>
    const config = await getConfig();

    return [
      {
        label: 'menu',
        submenu: [1, 2, 3].map((value) => ({
          label: `value ${value}`,
          type: 'radio',
          checked: config.value === value,
          click() {
            setConfig({ value });
          },
        })),
      },
    ];
  },

  backend: {
    start({ window, ipc }) {
      window.maximize();

      // you can communicate with renderer plugin
      ipc.handle('some-event', () => {
        return 'hello';
      });
    },
    // it fired when config changed
    onConfigChange(newConfig) { /* ... */ },
    // you can also clean up plugin
    stop(context) { /* ... */ },
  },
  renderer: {
    async start(context) {
      console.log(await context.ipc.invoke('some-event'));
    },
    // Only renderer available hook
    onPlayerApiReady(api: YoutubePlayer, context: RendererContext) {
      // set plugin config easily 
      context.setConfig({ myConfig: api.getVolume() });
    },
    onConfigChange(newConfig) { /* ... */ },
    stop(_context) { /* ... */ },
  },
  preload: {
    async start({ getConfig }) {
      const config = await getConfig();
    },
    onConfigChange(newConfig) {},
    stop(_context) {},
  },
});
```

# Notes
- resolves #1258
- resolves #1380
- resolves #1386
- resolves #1436

### CODE REVIEW

**Comment by JellyBrick** [comment]
cc @th-ch @ArjixWasTaken

**Comment by ArjixWasTaken** [comment]
Hmm, the plugins are not loaded fast enough, the visualizer doesn't apply if the video was loaded before it.

**Comment by ArjixWasTaken** [comment]
Also, I can't say that I am a fan of the design.

**Comment by th-ch** [comment]
I like some new features (like prompt to restart) but it seems some bugs were reported - it might be easier to have the new and old systems live side by side and migrate them one by one to easily review/test?

**Comment by ArjixWasTaken** [comment]
🎉

**Pull request merged**
