### PR TITLE
Added new websrv plugin

### PR DESCRIPTION
**Pull request by Krak8**
Added a new plugin to run a webserver in app.
We can control songs from this for more details read below: 

## **WebSrv**: Runs a webserver in the app. (used with combination with streamer bot check [here (Requires logging in to read.)](https://extensions.streamer.bot/t/youtube-music-integration-with-controls/777).)

- Play Music 
you can add music to queue and/or force play the music immediately.
`http://localhost:8888/play` & `http://localhost:8888/video` use following headers.
   >   | **Header** | **Value** | **Description** |
   >   | --- | --- | --- |
   >   | **name** | song name | This header takes the name of the song as input an adds it to the queue |
   >   | **force** | true/false | This header tells the YTMusic app to either add the song to the queue or forcefully play it immediately |

- Fetch last added song 
`http://localhost:8888/lastAdded` gives the name of the last added song.

- Play / Pause Music
`http://localhost:8888/playpause` allows you to toggle the state of music.
 
 - Play next song or previous song
   1. `http://localhost:8888/playnext` allows you to skip to the next song.
   2. `http://localhost:8888/playprevious` allows you to jump to the previous song.
 
- Queue
  `http://localhost:8888/queue` gives you song queue list.

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Is it really necessary to include express?
Also, please put a version prefix to all routes.

**Comment by ArjixWasTaken** [comment]
I see a lot of debug logs, if this is incomplete, please convert it to a draft PR.

**Comment by ArjixWasTaken** [comment]
> Express is necessary or it won't build. Express is used to run a webserver. Check this [server.ts file](https://github.com/th-ch/youtube-music/pull/1764/files#diff-8cee300d5b584b2705e48115bfcfce5b4b0c0971afaf1d49a3bf1d21a4a440f1)

That is a limitation imposed by the plugin author, @MrF1yn, not an actual requirement to set up a web server...
Node has this functionality built-in under the [http](https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener) module, in fact express is an [abstraction on-top of that](https://github.com/expressjs/express/blob/e720c5a21bfed5a9c73b2407797023bacad6980e/lib/application.js#L634).

> I am sorry, But I am not sure what routes you are referring to.

Since express was used, look at [their definition](https://expressjs.com/en/guide/routing.html) for what a route is...

> I don't think this is incomplete as I am using it and I am not the actual author for this plugin I am using this fork : [MrF1yn/youtube-music](https://github.com/MrF1yn/youtube-music)

Upon re-examining the code, my earlier assumptions were proven wrong, the code *works* the way it was designed to.
But I don't think it passes as quality code.

**Comment by ArjixWasTaken** [comment]
> if something needs to be changed then do let me know I will make the necessary changes. ✌️😁

Well, since you are not the author of the plugin, I doubt you'd want to do a huge rewrite to remove the express.js dependency.
But that is what I'd like you to do.

I don't think we are going to merge this as long as it requires any third party dependency.

**Comment by Krak8** [comment]
> > Express is necessary or it won't build. Express is used to run a webserver. Check this [server.ts file](https://github.com/th-ch/youtube-music/pull/1764/files#diff-8cee300d5b584b2705e48115bfcfce5b4b0c0971afaf1d49a3bf1d21a4a440f1)
> 
> That is a limitation imposed by the plugin author, @MrF1yn, not an actual requirement to set up a web server... Node has this functionality built-in under the [http](https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener) module, in fact express is an [abstraction on-top of that](https://github.com/expressjs/express/blob/e720c5a21bfed5a9c73b2407797023bacad6980e/lib/application.js#L634).
> 
> > I am sorry, But I am not sure what routes you are referring to.
> 
> Since express was used, look at [their definition](https://expressjs.com/en/guide/routing.html) for what a route is...
> 
> > I don't think this is incomplete as I am using it and I am not the actual author for this plugin I am using this fork : [MrF1yn/youtube-music](https://github.com/MrF1yn/youtube-music)
> 
> Upon re-examining the code, my earlier assumptions were proven wrong, the code _works_ the way it was designed to. But I don't think it passes as quality code.

@ArjixWasTaken Thanks for explaining things to me. I will close this pull request for now, but I will make necessary changes soon and create a new pull request. And regarding the routes it wasn't added because the port is customisable so that users can use custom port. If the routes needs to be prefixed do let me know. 

>Well, since you are not the author of the plugin, I doubt you'd want to do a huge rewrite to remove the express.js dependency.
But that is what I'd like you to do.
>
>I don't think we are going to merge this as long as it requires any third party dependency.

I will try to get this to work without any 3rd party dependency. I am a self-taught coder so I am not proficient with it. I might need to engage in some trial and errors to get it to work. 
 
 Thanks for your time and patience :)

**Comment by JellyBrick** [comment]
What about [Hono](https://www.npmjs.com/package/hono)? It has zero dependencies and fully supports TypeScript.

**Comment by ArjixWasTaken** [comment]
Hmm, Hono does look nice

**Comment by Destroy666x** [comment]
I went with Fastify within my incoming PR. What I definitely don't like in this one personally is ignoring any sort of REST principles, all the actions are just `GET`s.

**Comment by JellyBrick** [comment]
#1909

**Pull request closed without merging**
