### PR TITLE
FIX: Previous & Next Track Control

### PR DESCRIPTION
**Pull request by criticalsoft**

### CODE REVIEW

**Comment by Araxeus** [comment]
This really isn't smart since I just told you that the hotkeys on my pc are `j` and `k` like everyone

I can make an actual fix in the near future

**Comment by criticalsoft** [comment]
https://support.google.com/youtube/answer/7631406?hl=en

**Comment by Araxeus** [comment]
image
>I don't know why you are j / k binding.

I don't know why you don't 😋 (`shift`+`/` to see all shortcuts in the app) 

anyways I didn't actually check before writing my last comment sorry, the keybinds in this PR do actually work for me so it should probably be safe to merge

**Comment by criticalsoft** [comment]
20211112_231711_EPIC_ROCK__''Slingshot''_by_WattWhite_-_YouTube_- (chrome)

**Comment by Araxeus** [comment]
Bro what... this is a youtube-music application

I don't even know how or why you are watching normal youtube on here

**Comment by criticalsoft** [comment]
20211112_232132_EPIC_ROCK__''Slingshot''_by_WattWhite_-_YouTube (YouTube_Music)

**Comment by criticalsoft** [comment]
> 
> 
> > Because Electron Load YouTube, It's The Same.
> 
> no its not the same. this app was made for youtube-music only, all features and plugins are coded in a way that is specific to youtube-music, the start page is youtube-music, everything is just made in a specific way and not supposed to work on the normal youtube

I'm showing you the key binding part. Both youtube website and Electron app.

**Comment by Araxeus** [comment]
Both pictures you sent where on youtube.com . not music.youtube.com

How did you even navigate there? you are not intended to so

**Comment by criticalsoft** [comment]
> loaded
Sorry i don't care about other website so far.
And This app name is "YouTube Music"

**Comment by criticalsoft** [comment]
> 
> 
> Both pictures you sent were on youtube.com . not music.youtube.com
> 
> How did you even navigate there? you are not intended to so

Does music.youtube.com shortcut key Is J / K ?

**Comment by Araxeus** [comment]
If you don't want to use this app thats fine, but like I told you 10 times already, this app was made for [Youtube Music](music.youtube.com) and not for the normal youtube.

you can play all music from the normal youtube on here if you want, and yes the hotkeys are `j` + `k`

**Comment by criticalsoft** [comment]
> 
> 
> Bro what... this is a youtube-music application
> 
> I don't even know how or why you are watching normal youtube on here

I'm using this app to listen Normal YouTube Music.

**Comment by Araxeus** [comment]
Like I said, you can listen to all the music you have on [youtube.com](https://www.youtube.com) on [music.youtube,com](https://music.youtube.com/)

So I don't see whats the problem just using this app as intended

**Comment by criticalsoft** [comment]
> 
> 
> Like I said, you can listen to all the music you have on [youtube.com](https://www.youtube.com) on [music.youtube,com](https://music.youtube.com/) (same account, same songs, all connected)
> 
> So I don't see whats the problem just using this app as intended

The ShortCut Key is differrent.
So This Simple Fix Closed.

**Pull request closed without merging**
