### PR TITLE
chore(README): Nicer Readme 2.0

### PR DESCRIPTION
**Pull request by inson1**
1. Align name to center, it just look nicer, as badges, image and video below are also centered
2. Added content section
3. Changed order of product info (features and plugins) and download - Product info should be first, because from the start, people arent interested on how, but why should they install the app
4. Renamed Most asked questions to FAQ

I just need translate FAQ and Content

### CODE REVIEW

**Comment by inson1** [comment]
What do you think?

**Comment by VipelyWolfRS** [comment]
> 1. Align name to center, it just look nicer, as badges, image and video below are also centered
> 2. Added content section
> 3. Changed order of product info (features and plugins) and download - Product info should be first, because from the start, people arent interested on how, but why should they install the app
> 4. Renamed Most asked questions to FAQ
> 
> I just need translate FAQ and Content

what do you need translated?

**Comment by VipelyWolfRS** [comment]
> I just need translate FAQ and Content

Innihald (is)

**Comment by inson1** [comment]
@JellyBrick Is everything ok? Should I change something? 
What is ko translation?

**Comment by inson1** [comment]
I also now added link to AUR. There is one youtube-music-bin, but there are also youtube-music-git and youtube-music? Why?

**Comment by VipelyWolfRS** [comment]
> @VipelyWolfRS that is I guess Content, what is FAQ?

Algengar Spurningar

**Comment by JellyBrick** [comment]
> I also now added link to AUR. There is one youtube-music-bin, but there are also youtube-music-git and youtube-music. Why?

- `youtube-music-bin` means "install YTMD from released binaries"
- `youtube-music-git` means "install YTMD from https://github.com/th-ch/youtube-music (master branch)"
- `youtube-music` means "install YTMD from released source codes"

**Review by JellyBrick — APPROVED** [review]

**Pull request merged**
