### PR TITLE
Fixed canvas injected at the wrong position

### LINKED ISSUE #1233: Using Visualizer Results to black video screen
OS: Windows 11.
I'm not using any other plugins.
In the screenshot it's paused but looks exactly the same either way.

Not sure if I'm doing something wrong or if it's broken
Screenshot 2023-09-01 224159

### PR DESCRIPTION
**Pull request by MiepHD**
The wrong position caused that the canvas only showed up when `Plugins > video-toggle > Mode > Custom toggle` was enabled
It's now a child of #main-panel like in video-toggle.
Fixes #1233

### CODE REVIEW

**Review by th-ch — COMMENTED** [review]
With the change, the visualiser does not seem to work in full screen, is it expected?

**Comment by MiepHD** [comment]
Works the right way now 😅

**Comment by JellyBrick** [comment]
Could you incorporate this fix into #1235?

**Comment by th-ch** [comment]
Thanks for the fix, it has been applied in https://github.com/th-ch/youtube-music/commit/0229ccaa1ea5f69b37db415fac3ae033439a639e !

**Pull request closed without merging**
