### PR TITLE
Set activity to "Listening" instead of "Playing"

### PR DESCRIPTION
**Pull request by dvd-22**
It is a simple change but makes it 100x better when seeing my status on Discord. This is indeed possible as seen in [the code for the fork of discord.js used in this repository](https://github.com/xhayper/discord-rpc/blob/6683ce4abb75867ddde1b8ce31657de564f5ed0a/src/structures/ClientUser.ts#L75)

### CODE REVIEW

**Comment by Randrage** [comment]
Yes please! 👍

**Comment by WillCarlotto** [comment]
Yes! "Listening" should be the default

**Comment by myurtsev** [comment]
just merge it :)

**Review by myurtsev — APPROVED** [review]

**Comment by MulverineX** [comment]
@dvd-22 did you build the app locally to test this actually works? Last I checked custom activity types were not allowed by Discord by default

**Comment by dvd-22** [comment]
> @dvd-22 did you build the app locally to test if this actually works? Last I checked custom activity types were not allowed by Discord by default.

No, I didn't. I used discord.js v12 some time ago and it was allowed, so I just assumed it worked in newer versions. I will test it and update the pr accordingly.

**Comment by MulverineX** [comment]
Make sure when you test a friend can see the "Listening to" state as well. It might appear to work client-side but not actually be working.

**Comment by dvd-22** [comment]
I tested this, and sadly it doesn't work. It looks like activites set through IPC (not oauth activity.write scope) cannot set anything besides playing. Listening and Watching are overwritten by Discord to playing and the rest are blocked. So unless Discord changes something in their API, it won't be possible anytime soon.

**Pull request closed without merging**
