### PR TITLE
Allow Google Signin

### PR DESCRIPTION
**Pull request by WhiteHusky**
This doesn't truely fix the problem. A weird combination of refreshing several times and...generally spastastic navigation behavior seems to get around the signin. This is mostly here to show what I tried.

### CODE REVIEW

**Comment by WhiteHusky** [comment]
Related to #507

**Comment by WhiteHusky** [comment]
Gets weirder:

So after doing the weird navigation dance it kinda..._doesn't_ sign in correctly. It appears if you are, but you get a signed out front page. Removing the patch, signing in, then signing back in by clicking your signed out account it works.

Obviously this is broken.

**Comment by WhiteHusky** [comment]
More testing and trying to find a concise path to it working finds it's just a coinflip. Trying going back, forward, and several other navigations seems to be random when it'll just work or not. So I'm stumped.

I also tried just updating the user agent but no dice.

**Comment by Skaifer** [comment]
Hello! 
So I'm facing the same issue on Fedora using appimage. Just in case this info would help, I could not sign in to google account on Vivaldi until I turned on google's _**crypto token** extension_ in privacy settings. 

Cheers!

**Comment by Araxeus** [comment]
Hey could you try my PR? #515 

I think I might have fixed the problem 🙂

**Comment by Araxeus** [comment]
@WhiteHusky #515 was merged and should have fixed the problem

So this PR could be closed

**Comment by th-ch** [comment]
Closing as it should be fixed and the PR is stable - feel free to re-open a PR if needed!

**Pull request closed without merging**
