### PR TITLE
feat(api-server): Add repeat mode and seek time API

### LINKED ISSUE #2504: [Feature Request] (API Server): `GET api/v1/switch-repeat-mode`
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current variation of the API supports changing repeat modes only through iteration, but if the current mode is unknown, we cannot use iterations for precise mode selection.

### Proposed Solution

Add new `GET api/v1/switch-repeat-mode` to get current mode to calculate needed iteration or replace iterations with `off`, `all` and `one` modes.

### Alternatives Considered

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sent44**
I hate Javascript and its family now.

I do not define any type structures (and dont want to do it; dont know where to put it)
Just push this in my folk or do review comment thing idk and I will add it to PR. Same thing with the code order or rename something.

close #2504
maybe not close but good to know #2582

### CODE REVIEW

**Comment by JellyBrick** [comment]
Due to my personal circumstances, I can't review this PR before December 23. Sorry 🥲

**Review by JellyBrick — APPROVED** [review]

**Comment by JellyBrick** [comment]
Thanks!

**Comment by sent44** [comment]
Hello @JellyBrick ,
Thank you for the merged.
I understand the change in API, it is my bad because I never know it is already exist.
Did you accident nuke some of the seek-time code or did you planned to not merge this feature? Since you completely  remove it in #544b9e3 in another PR. (On phone, I cannot really fetch the name of PR and cannot remember its name)

**Comment by JellyBrick** [comment]
@sent44 The seek-time code does the same thing as song-info so you can use `/api/v1/song-info` instead.

**Pull request merged**
