### PR TITLE
fix: detect the upgrade btn using the icon

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
Fixes: #2363

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Assuming the name of the icon does not change, this should not break.
But even if it does break, it defaults back to the old way of removing the button.

(unless they decide to use an entirely different icon whilst the current one, `youtube_music_monochrome`, is still around)

**Comment by ArjixWasTaken** [comment]
@OpenRift412 would it be too much to ask if you could test this change?

(assuming you know how to run a dev build)

**Comment by OpenRift412** [comment]
> @OpenRift412 would it be too much to ask if you could test this change?
> 
> ~assuming you know how to run a dev build~ Actually, scratch that, you can just run
> 
> ```js
> const itemsSelector = 'ytmusic-guide-section-renderer #items';
> let selector = 'ytmusic-guide-entry-renderer:last-child';
> 
> const upgradeBtnIcon = document.querySelector('iron-iconset-svg[name="yt-sys-icons"] #youtube_music_monochrome');
> if (upgradeBtnIcon) {
>   const path = upgradeBtnIcon.firstChild;
>   const data = path.getAttribute('d').substring(0, 15);
>   selector = `ytmusic-guide-entry-renderer:has(> tp-yt-paper-item > yt-icon path[d^="${data}"])`;
> }
> 
> const styles = document.createElement('style');
> styles.textContent = `${itemsSelector} ${selector} { display: none; }`;
> document.head.appendChild(styles)
> ```
> 
> in your console after visiting https://music.youtube.com on your browser like this
> 
> image
> 
> If it doesn't remove the `Library` button, then all is fine.

I would need you to send me a compiled dev build.

**Comment by ArjixWasTaken** [comment]
Have you heard of the chrome/Firefox dev tools?

**Pull request merged**
